[pytest]

# 🔍 Файлы с тестами
python_files =
    test_*.py
    *_test.py
    homework_*.py
    test*.py
    make_screenshoot

# 📁 Пути для поиска тестов
testpaths =
    tests

# 🏷️ Маркеры тестов
markers =
    only:         🎯 Тесты только для subscription формы
    smoke:        🔥 Smoke тесты (критический функционал)
    regression:   🔄 Regression тесты
    play:         🎭 Тесты с использованием Playwright

# ⚙️ Параметры запуска
addopts =
;  ---- Основные настройки ----
    -v
    -s
    --maxfail=50
    --tb=short
    --strict-markers

;  ---- Playwright настройки ----
    -m play
    --headed
    --browser chromium
    --slowmo 1500

;  ---- 🧪 Параметры тестирования ----
    --tracing retain-on-failure
    --video retain-on-failure
    --screenshot on
    --output .test-results
    --numprocesses 1
    
;  ---- 🧾 Allure ----
    --alluredir .allure-results

python_classes =
    Test*
    *Test

filterwarnings = 
    ignore::pytest.PytestUnknownMarkWarning
    